using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MigrateDataLib.Schema.DefInfoItems;
using MigrateDataLib.Schema.Database;

namespace MigrateDataLib.OKmzdy.Schema
{
    public class DatabaseSchema : BaseDatabaseSchema
    {
        public DatabaseSchema(string ownerName, string usersName) : base(ownerName, usersName)
        {
        }

        public override IDictionary<string, TableDefInfo> CreateTableDictionary()
        {
            return new Dictionary<string, TableDefInfo>()
            {
                { TableStavDatabazeInfo.GetNameKey(), TableStavDatabazeInfo.GetDictValue(OwnerName, UsersName) },
                { TableFirmaInfo.GetNameKey(), TableFirmaInfo.GetDictValue(OwnerName, UsersName) },
                { TableSvatekInfo.GetNameKey(), TableSvatekInfo.GetDictValue(OwnerName, UsersName) },
                { TableAdresaInfo.GetNameKey(), TableAdresaInfo.GetDictValue(OwnerName, UsersName) },
                { TableBankSpojInfo.GetNameKey(), TableBankSpojInfo.GetDictValue(OwnerName, UsersName) },
                { TableOrganizaceInfo.GetNameKey(), TableOrganizaceInfo.GetDictValue(OwnerName, UsersName) },
                { TableUtvarInfo.GetNameKey(), TableUtvarInfo.GetDictValue(OwnerName, UsersName) },
                { TableDivizeStredInfo.GetNameKey(), TableDivizeStredInfo.GetDictValue(OwnerName, UsersName) },
                { TableStredCinzakInfo.GetNameKey(), TableStredCinzakInfo.GetDictValue(OwnerName, UsersName) },
                { TableStredRozpocetInfo.GetNameKey(), TableStredRozpocetInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavSemaforInfo.GetNameKey(), TableStavSemaforInfo.GetDictValue(OwnerName, UsersName) },
                { TableUzivatelInfo.GetNameKey(), TableUzivatelInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracVyberAggrInfo.GetNameKey(), TablePracVyberAggrInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracInfo.GetNameKey(), TablePracInfo.GetDictValue(OwnerName, UsersName) },
                { TableOsdataInfo.GetNameKey(), TableOsdataInfo.GetDictValue(OwnerName, UsersName) },
                { TablePojistitelInfo.GetNameKey(), TablePojistitelInfo.GetDictValue(OwnerName, UsersName) },
                { TableHlaseniZpInfo.GetNameKey(), TableHlaseniZpInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracNepritInfo.GetNameKey(), TablePracNepritInfo.GetDictValue(OwnerName, UsersName) },
                { TableDanInfo.GetNameKey(), TableDanInfo.GetDictValue(OwnerName, UsersName) },
                { TableSrazkaInfo.GetNameKey(), TableSrazkaInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerInfo.GetNameKey(), TablePpomerInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerDovInfo.GetNameKey(), TablePpomerDovInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerDovRokInfo.GetNameKey(), TablePpomerDovRokInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerMesInfo.GetNameKey(), TablePpomerMesInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerSumInfo.GetNameKey(), TablePpomerSumInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerOzpInfo.GetNameKey(), TablePpomerOzpInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerPraxeInfo.GetNameKey(), TablePpomerPraxeInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomerSluzbaInfo.GetNameKey(), TablePpomerSluzbaInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracVzdelavaniInfo.GetNameKey(), TablePracVzdelavaniInfo.GetDictValue(OwnerName, UsersName) },
                { TablePrijmySspInfo.GetNameKey(), TablePrijmySspInfo.GetDictValue(OwnerName, UsersName) },
                { TablePrijmyInfo.GetNameKey(), TablePrijmyInfo.GetDictValue(OwnerName, UsersName) },
                { TablePrijmy1500Info.GetNameKey(), TablePrijmy1500Info.GetDictValue(OwnerName, UsersName) },
                { TableProhlaseniInfo.GetNameKey(), TableProhlaseniInfo.GetDictValue(OwnerName, UsersName) },
                { TableRodinaInfo.GetNameKey(), TableRodinaInfo.GetDictValue(OwnerName, UsersName) },
                { TablePrijmyMesInfo.GetNameKey(), TablePrijmyMesInfo.GetDictValue(OwnerName, UsersName) },
                { TableMzdaInfo.GetNameKey(), TableMzdaInfo.GetDictValue(OwnerName, UsersName) },
                { TableNepritInfo.GetNameKey(), TableNepritInfo.GetDictValue(OwnerName, UsersName) },
                { TableUvazekInfo.GetNameKey(), TableUvazekInfo.GetDictValue(OwnerName, UsersName) },
                { TableUzivDataPpomerInfo.GetNameKey(), TableUzivDataPpomerInfo.GetDictValue(OwnerName, UsersName) },
                { TableUzivReldpDavkaInfo.GetNameKey(), TableUzivReldpDavkaInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracReldpDataInfo.GetNameKey(), TablePracReldpDataInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracReldpListekInfo.GetNameKey(), TablePracReldpListekInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracReldp09DataPracInfo.GetNameKey(), TablePracReldp09DataPracInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracReldp09DataPojInfo.GetNameKey(), TablePracReldp09DataPojInfo.GetDictValue(OwnerName, UsersName) },
                { TablePlatbyKonfigInfo.GetNameKey(), TablePlatbyKonfigInfo.GetDictValue(OwnerName, UsersName) },
                { TablePlatbyUtvaryInfo.GetNameKey(), TablePlatbyUtvaryInfo.GetDictValue(OwnerName, UsersName) },
                { TablePopisSlozkaInfo.GetNameKey(), TablePopisSlozkaInfo.GetDictValue(OwnerName, UsersName) },
                { TablePopisSlozkaHInfo.GetNameKey(), TablePopisSlozkaHInfo.GetDictValue(OwnerName, UsersName) },
                { TablePopisSlozkaTInfo.GetNameKey(), TablePopisSlozkaTInfo.GetDictValue(OwnerName, UsersName) },
                { TableTarifniTridaInfo.GetNameKey(), TableTarifniTridaInfo.GetDictValue(OwnerName, UsersName) },
                { TableTarifniTridaHInfo.GetNameKey(), TableTarifniTridaHInfo.GetDictValue(OwnerName, UsersName) },
                { TableTarifniTridaTInfo.GetNameKey(), TableTarifniTridaTInfo.GetDictValue(OwnerName, UsersName) },
                { TableUcetniOsnovaInfo.GetNameKey(), TableUcetniOsnovaInfo.GetDictValue(OwnerName, UsersName) },
                { TableUcetniPredpisyInfo.GetNameKey(), TableUcetniPredpisyInfo.GetDictValue(OwnerName, UsersName) },
                { TableUcetniPolozkyInfo.GetNameKey(), TableUcetniPolozkyInfo.GetDictValue(OwnerName, UsersName) },
                { TableUzivCiselnikInfo.GetNameKey(), TableUzivCiselnikInfo.GetDictValue(OwnerName, UsersName) },
                { TableValutaKurzInfo.GetNameKey(), TableValutaKurzInfo.GetDictValue(OwnerName, UsersName) },
                { TableValutaKurzMesInfo.GetNameKey(), TableValutaKurzMesInfo.GetDictValue(OwnerName, UsersName) },
                { TableZemePlatkoefInfo.GetNameKey(), TableZemePlatkoefInfo.GetDictValue(OwnerName, UsersName) },
                { TableZemePlatkoefMesInfo.GetNameKey(), TableZemePlatkoefMesInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavKonfigInfo.GetNameKey(), TableStavKonfigInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavKonfigUcertInfo.GetNameKey(), TableStavKonfigUcertInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavKonfigSmtpInfo.GetNameKey(), TableStavKonfigSmtpInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavKonfigVrepInfo.GetNameKey(), TableStavKonfigVrepInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavMesInfo.GetNameKey(), TableStavMesInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavMesDanInfo.GetNameKey(), TableStavMesDanInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavStatInfo.GetNameKey(), TableStavStatInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavDefaultInfo.GetNameKey(), TableStavDefaultInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavOzpInfo.GetNameKey(), TableStavOzpInfo.GetDictValue(OwnerName, UsersName) },
                { TableStavMessageInfo.GetNameKey(), TableStavMessageInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyHtmlInfo.GetNameKey(), TableSestavyHtmlInfo.GetDictValue(OwnerName, UsersName) },
                { TablePoplatkyInfo.GetNameKey(), TablePoplatkyInfo.GetDictValue(OwnerName, UsersName) },
                { TableDetailMediaInfo.GetNameKey(), TableDetailMediaInfo.GetDictValue(OwnerName, UsersName) },
                { TableFiltrMediaInfo.GetNameKey(), TableFiltrMediaInfo.GetDictValue(OwnerName, UsersName) },
                { TableFiltrPmediaInfo.GetNameKey(), TableFiltrPmediaInfo.GetDictValue(OwnerName, UsersName) },
                { TableFiltrUmediaInfo.GetNameKey(), TableFiltrUmediaInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyFiltrInfo.GetNameKey(), TableSestavyFiltrInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyLstInfo.GetNameKey(), TableSestavyLstInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyUdataInfo.GetNameKey(), TableSestavyUdataInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyUlstInfo.GetNameKey(), TableSestavyUlstInfo.GetDictValue(OwnerName, UsersName) },
                { TableSestavyUzivInfo.GetNameKey(), TableSestavyUzivInfo.GetDictValue(OwnerName, UsersName) },
                { TableSberneMediumInfo.GetNameKey(), TableSberneMediumInfo.GetDictValue(OwnerName, UsersName) },
                { TablePlatebniMediumInfo.GetNameKey(), TablePlatebniMediumInfo.GetDictValue(OwnerName, UsersName) },
                { TableUcetniMediumInfo.GetNameKey(), TableUcetniMediumInfo.GetDictValue(OwnerName, UsersName) },
                { TableNavestiFiltrInfo.GetNameKey(), TableNavestiFiltrInfo.GetDictValue(OwnerName, UsersName) },
                { TableNavestiUzivInfo.GetNameKey(), TableNavestiUzivInfo.GetDictValue(OwnerName, UsersName) },
                { TablePracUkazateleInfo.GetNameKey(), TablePracUkazateleInfo.GetDictValue(OwnerName, UsersName) },
                { TablePpomUkazateleInfo.GetNameKey(), TablePpomUkazateleInfo.GetDictValue(OwnerName, UsersName) },
                { TableVrepPodaniDataInfo.GetNameKey(), TableVrepPodaniDataInfo.GetDictValue(OwnerName, UsersName) },
                { TableExcelUimpInfo.GetNameKey(), TableExcelUimpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestSoczdrPaymsInfo.GetNameKey(), TableZsestSoczdrPaymsInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanZvyhodneInfo.GetNameKey(), TableZsestDanZvyhodneInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanOznameniInfo.GetNameKey(), TableZsestDanOznameniInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestExtMzdlistInfo.GetNameKey(), TableZsestExtMzdlistInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanPrijmyInfo.GetNameKey(), TableZsestDanPrijmyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanPotvrzeniInfo.GetNameKey(), TableZsestDanPotvrzeniInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanPotvr1500Info.GetNameKey(), TableZsestDanPotvr1500Info.GetDictValue(OwnerName, UsersName) },
                { TableZsestDanHlaseni5478Info.GetNameKey(), TableZsestDanHlaseni5478Info.GetDictValue(OwnerName, UsersName) },
                { TableZsestDavkaUcetniInfo.GetNameKey(), TableZsestDavkaUcetniInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestEldp2004Info.GetNameKey(), TableZsestEldp2004Info.GetDictValue(OwnerName, UsersName) },
                { TableZsestMlmesiceInfo.GetNameKey(), TableZsestMlmesiceInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestMlnepritInfo.GetNameKey(), TableZsestMlnepritInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestMlnezdanInfo.GetNameKey(), TableZsestMlnezdanInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestMlpomeryInfo.GetNameKey(), TableZsestMlpomeryInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestMlpracovInfo.GetNameKey(), TableZsestMlpracovInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestNemDavkyInfo.GetNameKey(), TableZsestNemDavkyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPlatbyCrInfo.GetNameKey(), TableZsestPlatbyCrInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPlatbyEuroInfo.GetNameKey(), TableZsestPlatbyEuroInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPrijemSspInfo.GetNameKey(), TableZsestPrijemSspInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestRekapitInfo.GetNameKey(), TableZsestRekapitInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestSocialInfo.GetNameKey(), TableZsestSocialInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDsporHlascaInfo.GetNameKey(), TableZsestDsporHlascaInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDsporHlasnaInfo.GetNameKey(), TableZsestDsporHlasnaInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDsporVyuctInfo.GetNameKey(), TableZsestDsporVyuctInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvrzDpInfo.GetNameKey(), TableZsestPotvrzDpInfo.GetDictValue(OwnerName, UsersName) },
                { TableMzvIisspPredpisyInfo.GetNameKey(), TableMzvIisspPredpisyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestUzivSestInfo.GetNameKey(), TableZsestUzivSestInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestVypDaneInfo.GetNameKey(), TableZsestVypDaneInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestVyplListinyInfo.GetNameKey(), TableZsestVyplListinyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestVyplListkyInfo.GetNameKey(), TableZsestVyplListkyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestVyuctZmenyInfo.GetNameKey(), TableZsestVyuctZmenyInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZdravInfo.GetNameKey(), TableZsestZdravInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZmenyZpInfo.GetNameKey(), TableZsestZmenyZpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetadInfo.GetNameKey(), TableZsestDpzvd2VetadInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetaoInfo.GetNameKey(), TableZsestDpzvd2VetaoInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvs2VetaoInfo.GetNameKey(), TableZsestDpzvs2VetaoInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetaeInfo.GetNameKey(), TableZsestDpzvd2VetaeInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvs2VetaeInfo.GetNameKey(), TableZsestDpzvs2VetaeInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetafInfo.GetNameKey(), TableZsestDpzvd2VetafInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetagInfo.GetNameKey(), TableZsestDpzvd2VetagInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetabInfo.GetNameKey(), TableZsestDpzvd2VetabInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestDpzvd2VetacInfo.GetNameKey(), TableZsestDpzvd2VetacInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPpomerPraxeInfo.GetNameKey(), TableZsestPpomerPraxeInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvrzHlavInfo.GetNameKey(), TableZsestPotvrzHlavInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPot313VedlInfo.GetNameKey(), TableZsestPot313VedlInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPot313NeschInfo.GetNameKey(), TableZsestPot313NeschInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPot313PohlInfo.GetNameKey(), TableZsestPot313PohlInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvrzZpInfo.GetNameKey(), TableZsestPotvrzZpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvrzSpInfo.GetNameKey(), TableZsestPotvrzSpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestKontrZdrpInfo.GetNameKey(), TableZsestKontrZdrpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestKontrSocpInfo.GetNameKey(), TableZsestKontrSocpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestOznamSocpInfo.GetNameKey(), TableZsestOznamSocpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPrehlSocpInfo.GetNameKey(), TableZsestPrehlSocpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPrilohaSocpInfo.GetNameKey(), TableZsestPrilohaSocpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestSlevySocpInfo.GetNameKey(), TableZsestSlevySocpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestNemDavky09Info.GetNameKey(), TableZsestNemDavky09Info.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadNemInfo.GetNameKey(), TableZsestZadNemInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadNemNeschInfo.GetNameKey(), TableZsestZadNemNeschInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadNemRozhobdInfo.GetNameKey(), TableZsestZadNemRozhobdInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadMatInfo.GetNameKey(), TableZsestZadMatInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadMatNeschInfo.GetNameKey(), TableZsestZadMatNeschInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadMatRozhobdInfo.GetNameKey(), TableZsestZadMatRozhobdInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvdavSspInfo.GetNameKey(), TableZsestPotvdavSspInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestReldp09PracInfo.GetNameKey(), TableZsestReldp09PracInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestReldp09PojInfo.GetNameKey(), TableZsestReldp09PojInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPrehvyuctfinInfo.GetNameKey(), TableZsestPrehvyuctfinInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotVptInfo.GetNameKey(), TableZsestPotVptInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotVptRozhobdInfo.GetNameKey(), TableZsestPotVptRozhobdInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPrehlZdrpInfo.GetNameKey(), TableZsestPrehlZdrpInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestZadostBonusmrInfo.GetNameKey(), TableZsestZadostBonusmrInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestPotvvrzOsr111Info.GetNameKey(), TableZsestPotvvrzOsr111Info.GetDictValue(OwnerName, UsersName) },
                { TableZsestKartazZaklInfo.GetNameKey(), TableZsestKartazZaklInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestKartazPpozInfo.GetNameKey(), TableZsestKartazPpozInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestKartazVzdvInfo.GetNameKey(), TableZsestKartazVzdvInfo.GetDictValue(OwnerName, UsersName) },
                { TableZsestKartazPpomInfo.GetNameKey(), TableZsestKartazPpomInfo.GetDictValue(OwnerName, UsersName) },
                //{ TablePopisAuditText.GetNameKey(), TablePopisAuditText.GetDictValue(OwnerName, UsersName) },
                //{ TableAuditUdalost.GetNameKey(), TableAuditUdalost.GetDictValue(OwnerName, UsersName) },
                //{ TableAuditZaznamHist.GetNameKey(), TableAuditZaznamHist.GetDictValue(OwnerName, UsersName) },
                //{ VyberAuditZaznamHist.GetNameKey(), VyberAuditZaznamHist.GetDictValue(OwnerName, UsersName) },
                //{ TableImportCsvKonfig.GetNameKey(), TableImportCsvKonfig.GetDictValue(OwnerName, UsersName) },
                //{ TableImportCsvKonfigCols.GetNameKey(), TableImportCsvKonfigCols.GetDictValue(OwnerName, UsersName) },
                //{ TableImportCsvDavka.GetNameKey(), TableImportCsvDavka.GetDictValue(OwnerName, UsersName) },
                //{ TableImportPersRadka.GetNameKey(), TableImportPersRadka.GetDictValue(OwnerName, UsersName) },
                //{ TableImportPersIdentif.GetNameKey(), TableImportPersIdentif.GetDictValue(OwnerName, UsersName) },
                //{ TableImportPolozkaData.GetNameKey(), TableImportPolozkaData.GetDictValue(OwnerName, UsersName) },
                //{ TableImportProtokolDavka.GetNameKey(), TableImportProtokolDavka.GetDictValue(OwnerName, UsersName) },
                //{ TableImportProtokolData.GetNameKey(), TableImportProtokolData.GetDictValue(OwnerName, UsersName) },
                //{ VyberPracPPomerList.GetNameKey(), VyberPracPPomerList.GetDictValue(OwnerName, UsersName) },
                //{ VyberImportCsvHist.GetNameKey(), VyberImportCsvHist.GetDictValue(OwnerName, UsersName) },
                //{ VyberPersonsCsvHist.GetNameKey(), VyberPersonsCsvHist.GetDictValue(OwnerName, UsersName) },
                //{ VyberPersPolCsvHist.GetNameKey(), VyberPersPolCsvHist.GetDictValue(OwnerName, UsersName) },
                //{ VyberPolozkaCsvHist.GetNameKey(), VyberPolozkaCsvHist.GetDictValue(OwnerName, UsersName) },
                //{ VyberProtokolCsvHist.GetNameKey(), VyberProtokolCsvHist.GetDictValue(OwnerName, UsersName) },
                //{ TableZsestParVyplListkyInfo.GetNameKey(), TableZsestParVyplListkyInfo.GetDictValue(OwnerName, UsersName) },
            };
        }
        public override IDictionary<string, QueryDefInfo> CreateQueryDictionary()
        {
            return new Dictionary<string, QueryDefInfo>()
            {
                { QueryKrokujPracPocitanyInfo.GetNameKey(), QueryKrokujPracPocitanyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryKrokujPracovnikyInfo.GetNameKey(), QueryKrokujPracovnikyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracZarazeniInfo.GetNameKey(), QueryVyberPracZarazeniInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPPomZarazeniInfo.GetNameKey(), QueryVyberPPomZarazeniInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracOpravneniInfo.GetNameKey(), QueryVyberPracOpravneniInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracovnikyFiltrXOInfo.GetNameKey(), QueryVyberPracovnikyFiltrXOInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracovnikyFiltrXPInfo.GetNameKey(), QueryVyberPracovnikyFiltrXPInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracovnikyFiltrXZInfo.GetNameKey(), QueryVyberPracovnikyFiltrXZInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracovnikyFiltrZPInfo.GetNameKey(), QueryVyberPracovnikyFiltrZPInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracPocitanyInfo.GetNameKey(), QueryVyberPracPocitanyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPracovnikyInfo.GetNameKey(), QueryVyberPracovnikyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberUtvaryInfo.GetNameKey(), QueryVyberUtvaryInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberSestavyInfo.GetNameKey(), QueryVyberSestavyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberSbMediaInfo.GetNameKey(), QueryVyberSbMediaInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberPlMediaInfo.GetNameKey(), QueryVyberPlMediaInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberUcMediaInfo.GetNameKey(), QueryVyberUcMediaInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberUcetPrPolozkyInfo.GetNameKey(), QueryVyberUcetPrPolozkyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryHodnExtMListInfo.GetNameKey(), QueryHodnExtMListInfo.GetDictValue(OwnerName, UsersName) },
                { QueryCelkExtMListInfo.GetNameKey(), QueryCelkExtMListInfo.GetDictValue(OwnerName, UsersName) },
                { QueryHodnVyuctFinInfo.GetNameKey(), QueryHodnVyuctFinInfo.GetDictValue(OwnerName, UsersName) },
                { QueryCelkVyuctFinInfo.GetNameKey(), QueryCelkVyuctFinInfo.GetDictValue(OwnerName, UsersName) },
                { QuerySocialInfo.GetNameKey(), QuerySocialInfo.GetDictValue(OwnerName, UsersName) },
                { QuerySumaDanInfo.GetNameKey(), QuerySumaDanInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyplListkySortInfo.GetNameKey(), QueryVyplListkySortInfo.GetDictValue(OwnerName, UsersName) },
                { QueryMzvIIsspPredpisyInfo.GetNameKey(), QueryMzvIIsspPredpisyInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberReldp09DavkaInfo.GetNameKey(), QueryVyberReldp09DavkaInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberReldp09DataInfo.GetNameKey(), QueryVyberReldp09DataInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberReldpDavkaInfo.GetNameKey(), QueryVyberReldpDavkaInfo.GetDictValue(OwnerName, UsersName) },
                { QueryVyberReldpDataInfo.GetNameKey(), QueryVyberReldpDataInfo.GetDictValue(OwnerName, UsersName) },
            };
        }

    }
}
